export const RESOURCE_CATEGORIES = [
  { id: 'all', label: 'All help', labelHi: 'सब मदद' },
  { id: 'safety', label: 'Safety & rights', labelHi: 'सुरक्षा और अधिकार' },
  { id: 'health', label: 'Health & motherhood', labelHi: 'स्वास्थ्य और मातृत्व' },
  { id: 'money', label: 'Money & documents', labelHi: 'पैसे और कागज़' },
  { id: 'work', label: 'Work & skills', labelHi: 'काम और कौशल' },
  { id: 'business', label: 'Business & livelihood', labelHi: 'व्यवसाय और रोज़गार' },
  { id: 'family', label: 'Family & welfare', labelHi: 'परिवार और कल्याण' },
];

export const RESOURCE_CATALOG = [
  {
    id: 'emergency-112', category: 'safety', icon: 'safety', priority: 1,
    title: '112 India emergency help', titleHi: '112 भारत आपातकालीन मदद',
    summary: 'Call 112 for urgent police, fire, ambulance, or safety help.', summaryHi: 'पुलिस, आग, एम्बुलेंस या तुरंत सुरक्षा मदद के लिए 112 पर कॉल करें।',
    whatFor: 'A single emergency number that works across India.',
    nextStep: 'If someone is in immediate danger, call 112 now.', nextStepHi: 'अगर अभी खतरा है, तो 112 पर तुरंत कॉल करें।',
    phone: '112', officialUrl: 'https://112.gov.in/', keywords: ['emergency', 'danger', 'police', 'ambulance', 'fire', 'सुरक्षा', 'खतरा', 'पुलिस', 'आपातकाल', 'அவசரம்', 'అత్యవసరం', 'आणीबाणी', 'ತುರ್ತು', 'કટોકટી', 'അടിയന്തര', 'ਐਮਰਜੈਂਸੀ', 'ଜରୁରୀ', 'জৰুৰী', 'ایمرجنسی'],
  },
  {
    id: 'women-helpline-181', category: 'safety', icon: 'safety', priority: 2,
    title: 'Women Helpline 181', titleHi: 'महिला हेल्पलाइन 181',
    summary: 'Get information, support, and a connection to local women’s services.', summaryHi: 'जानकारी, मदद और नज़दीकी महिला सेवा से जुड़ने के लिए 181 पर कॉल करें।',
    whatFor: 'Women facing violence, distress, or needing scheme and support information.',
    nextStep: 'Call 181, or ask a trusted person to call with you.', nextStepHi: '181 पर कॉल करें या किसी भरोसेमंद व्यक्ति से साथ में कॉल करवाएं।',
    phone: '181', officialUrl: 'https://missionshakti.wcd.gov.in/', keywords: ['women helpline', 'violence', 'distress', '181', 'महिला हेल्पलाइन', 'हिंसा', 'பெண்கள் உதவி', 'మహిళా హెల్ప్‌లైన్', 'ಮಹಿಳಾ ಸಹಾಯವಾಣಿ', 'મહિલા હેલ્પલાઇન', 'വനിതാ ഹെൽപ്‌ലൈൻ', 'ਮਹਿਲਾ ਹੈਲਪਲਾਈਨ', 'ମହିଳା ହେଲ୍ପଲାଇନ', 'মহিলা হেল্পলাইন', 'خواتین ہیلپ لائن'],
  },
  {
    id: 'cyber-crime-1930', category: 'safety', icon: 'safety', priority: 3,
    title: 'Cyber Crime Reporting Portal', titleHi: 'साइबर अपराध शिकायत',
    summary: 'Report online fraud, abusive messages, or cybercrime against women and children.', summaryHi: 'ऑनलाइन ठगी, गंदे संदेश या महिलाओं और बच्चों के खिलाफ साइबर अपराध की शिकायत करें।',
    whatFor: 'Online financial fraud, impersonation, threats, and other cybercrime.',
    nextStep: 'For a money fraud, call 1930 quickly and keep the transaction details ready.', nextStepHi: 'पैसों की ठगी हो तो तुरंत 1930 पर कॉल करें और लेन-देन की जानकारी रखें।',
    phone: '1930', officialUrl: 'https://cybercrime.gov.in/', keywords: ['cyber', 'fraud', 'online fraud', 'scam', '1930', 'साइबर', 'ठगी', 'फ्रॉड', 'சைபர்', 'மோசடி', 'సైబర్', 'మోసం', 'सायबर', 'फसवणूक', 'ಸೈಬರ್', 'ಮೋಸ', 'સાયબર', 'છેતરપિંડી', 'സൈബർ', 'തട്ടിപ്പ്', 'ਸਾਈਬਰ', 'ਧੋਖਾ', 'ସାଇବର', 'ଠକେଇ', 'চাইবাৰ', 'প্ৰৱঞ্চনা', 'سائبر', 'فراڈ'],
  },
  {
    id: 'ncw-complaint', category: 'safety', icon: 'rights', priority: 4,
    title: 'National Commission for Women complaint', titleHi: 'राष्ट्रीय महिला आयोग शिकायत',
    summary: 'Register or track a complaint about violation of women’s rights.', summaryHi: 'महिलाओं के अधिकारों के उल्लंघन की शिकायत दर्ज करें या उसकी स्थिति देखें।',
    whatFor: 'Domestic violence, harassment, dowry, desertion, discrimination, or other rights concerns.',
    nextStep: 'Open the complaint portal and write the facts, dates, and help you need. Do not share OTPs or passwords.', nextStepHi: 'पोर्टल खोलकर घटना, तारीख और अपनी ज़रूरत लिखें। OTP या पासवर्ड साझा न करें।',
    officialUrl: 'https://ncwapps.nic.in/', keywords: ['ncw', 'complaint', 'rights', 'harassment', 'dowry', 'शिकायत', 'अधिकार', 'दहेज'],
  },
  {
    id: 'nalsa-legal-aid', category: 'safety', icon: 'rights', priority: 5,
    title: 'Free legal aid for women', titleHi: 'महिलाओं के लिए मुफ्त कानूनी सहायता',
    summary: 'Find free legal help through NALSA and local legal services authorities.', summaryHi: 'NALSA और स्थानीय कानूनी सेवा प्राधिकरण से मुफ्त कानूनी मदद लें।',
    whatFor: 'A woman can seek free legal services irrespective of income, subject to the service process.',
    nextStep: 'Call 15100 or contact the nearest District Legal Services Authority.', nextStepHi: '15100 पर कॉल करें या नज़दीकी जिला विधिक सेवा प्राधिकरण से संपर्क करें।',
    phone: '15100', officialUrl: 'https://nalsa.gov.in/womens-assistance/', keywords: ['legal aid', 'lawyer', 'court', '15100', 'कानूनी मदद', 'वकील', 'अदालत', 'சட்ட உதவி', 'வழக்கறிஞர்', 'న్యాయ సహాయం', 'कायदेशीर मदत', 'ಕಾನೂನು ಸಹಾಯ', 'વકીલ', 'നിയമ സഹായം', 'ਕਾਨੂੰਨੀ ਮਦਦ', 'ଆଇନ ସହାୟତା', 'আইনী সহায়তা', 'قانونی مدد'],
  },
  {
    id: 'pmmvy', category: 'health', icon: 'health', priority: 1,
    title: 'Pradhan Mantri Matru Vandana Yojana', titleHi: 'प्रधानमंत्री मातृ वंदना योजना',
    summary: 'Maternity benefit information for eligible pregnant and lactating mothers.', summaryHi: 'पात्र गर्भवती और स्तनपान कराने वाली माताओं के लिए मातृत्व लाभ की जानकारी।',
    whatFor: 'Maternity support delivered through the government’s women and child development system.',
    nextStep: 'Ask your Anganwadi worker or visit the official PMMVY portal to check the current process.', nextStepHi: 'अपनी आंगनवाड़ी कार्यकर्ता से पूछें या PMMVY पोर्टल पर वर्तमान प्रक्रिया देखें।',
    officialUrl: 'https://pmmvy.wcd.gov.in/', keywords: ['pregnant', 'maternity', 'mother', 'baby', 'pmmvy', 'गर्भवती', 'मातृत्व', 'बच्चा', 'கர்ப்பம்', 'தாய்மை', 'గర్భం', 'మాతృత్వం', 'गर्भावस्था', 'गर्भधारणा', 'ಮಾತೃತ್ವ', 'ગર્ભાવસ્થા', 'മാതൃത്വം', 'ਮਾਤൃത്വ', 'ଗର୍ଭଧାରଣ', 'মাতৃত্ব', 'حمل', 'زچگی'],
  },
  {
    id: 'pmjay', category: 'health', icon: 'health', priority: 2,
    title: 'Ayushman Bharat PM-JAY', titleHi: 'आयुष्मान भारत PM-JAY',
    summary: 'Check health coverage and find the official beneficiary and hospital services.', summaryHi: 'स्वास्थ्य कवरेज और सरकारी अस्पताल की आधिकारिक सेवाओं की जानकारी देखें।',
    whatFor: 'Eligible families seeking cashless hospital care under the national health assurance system.',
    nextStep: 'Use the official portal to check eligibility or ask an Ayushman desk at a listed hospital.', nextStepHi: 'पात्रता पोर्टल पर देखें या सूचीबद्ध अस्पताल के आयुष्मान डेस्क पर पूछें।',
    officialUrl: 'https://pmjay.gov.in/', keywords: ['health insurance', 'hospital', 'ayushman', 'pmjay', 'इलाज', 'अस्पताल', 'स्वास्थ्य', 'சிகிச்சை', 'மருத்துவமனை', 'ఆసుపత్రి', 'చికిత్స', 'उपचार', 'रुग्णालय', 'ಆಸ್ಪತ್ರೆ', 'સારવાર', 'ആശുപത്രി', 'ਇਲਾਜ', 'ହସ୍ପିଟାଲ', 'চিকিৎসা', 'ہسپتال', 'علاج'],
  },
  {
    id: 'esanjeevani', category: 'health', icon: 'health', priority: 3,
    title: 'eSanjeevani telemedicine', titleHi: 'ई-संजीवनी ऑनलाइन डॉक्टर',
    summary: 'Connect with a government telemedicine service when travelling to a facility is difficult.', summaryHi: 'जब अस्पताल जाना मुश्किल हो, सरकारी टेलीमेडिसिन सेवा से जुड़ें।',
    whatFor: 'Remote consultation and health guidance through the national telemedicine service.',
    nextStep: 'Open eSanjeevani and follow the patient registration instructions. Use 112 for emergencies.', nextStepHi: 'ई-संजीवनी खोलकर मरीज पंजीकरण के निर्देश मानें। आपातकाल में 112 पर कॉल करें।',
    officialUrl: 'https://esanjeevani.mohfw.gov.in/', keywords: ['doctor', 'telemedicine', 'health', 'online doctor', 'डॉक्टर', 'ऑनलाइन इलाज'],
  },
  {
    id: 'janani-suraksha', category: 'health', icon: 'health', priority: 4,
    title: 'Janani Suraksha Yojana', titleHi: 'जननी सुरक्षा योजना',
    summary: 'Information about support that encourages institutional delivery for eligible women.', summaryHi: 'पात्र महिलाओं के लिए संस्थागत प्रसव से जुड़ी सहायता की जानकारी।',
    whatFor: 'Pregnant women who need to understand public-facility delivery support.',
    nextStep: 'Ask your ASHA worker, ANM, or government health facility about the current eligibility and process.', nextStepHi: 'अपनी आशा कार्यकर्ता, ANM या सरकारी स्वास्थ्य केंद्र से पात्रता और प्रक्रिया पूछें।',
    officialUrl: 'https://nhm.gov.in/', keywords: ['delivery', 'pregnancy', 'asha', 'anm', 'जननी', 'प्रसव', 'गर्भावस्था'],
  },
  {
    id: 'pmuy-new-connection', category: 'family', icon: 'family', priority: 1,
    title: 'Pradhan Mantri Ujjwala Yojana', titleHi: 'प्रधानमंत्री उज्ज्वला योजना',
    summary: 'Guidance for eligible women who need an LPG connection at home.', summaryHi: 'जिन पात्र महिलाओं को घर में LPG कनेक्शन चाहिए, उनके लिए मार्गदर्शन।',
    whatFor: 'A household without an LPG connection that wants to understand the Ujjwala route.',
    nextStep: 'Keep your family and address documents ready, then approach an LPG distributor or the official PMUY site.', nextStepHi: 'परिवार और पते के कागज़ रखें, फिर LPG वितरक या PMUY की आधिकारिक वेबसाइट पर जाएं।',
    officialUrl: 'https://www.pmuy.gov.in/ujjwala2.html', keywords: ['gas', 'lpg', 'ujjwala', 'cylinder', 'गैस', 'सिलेंडर', 'उज्ज्वला', 'எரிவாயு', 'గ్యాస్', 'गॅस', 'ಗ್ಯಾಸ್', 'ગેસ', 'ഗ്യാസ്', 'ਗੈਸ', 'ଗ୍ୟାସ', 'গ্যাস', 'گیس'],
  },
  {
    id: 'pmjdy', category: 'money', icon: 'money', priority: 1,
    title: 'Pradhan Mantri Jan-Dhan Yojana', titleHi: 'प्रधानमंत्री जन-धन योजना',
    summary: 'Open or understand a basic bank account and access financial services.', summaryHi: 'बेसिक बैंक खाता खोलने और वित्तीय सेवाओं की जानकारी लें।',
    whatFor: 'People without a bank account who need savings, direct benefit transfer, insurance, or pension access.',
    nextStep: 'Visit a bank branch or Bank Mitra and ask for a basic savings account under PMJDY.', nextStepHi: 'बैंक शाखा या बैंक मित्र के पास जाकर PMJDY का बेसिक बचत खाता पूछें।',
    officialUrl: 'https://www.pmjdy.gov.in/', keywords: ['bank', 'account', 'jan dhan', 'money', 'बैंक', 'खाता', 'जन धन', 'வங்கி', 'கணக்கு', 'బ్యాంక్', 'ఖాతా', 'बँक', 'खाते', 'ಬ್ಯಾಂಕ್', 'ಖಾತೆ', 'બેંક', 'ખાતું', 'ബാങ്ക്', 'അക്കൗണ്ട്', 'ਬੈਂਕ', 'ਖਾਤਾ', 'ବ୍ୟାଙ୍କ', 'ଖାତା', 'বেংক', 'একাউণ্ট', 'بینک', 'اکاؤنٹ'],
  },
  {
    id: 'eshram', category: 'money', icon: 'work', priority: 2,
    title: 'eShram worker registration', titleHi: 'ई-श्रम पंजीकरण',
    summary: 'Create an official record for an eligible unorganised worker and discover linked schemes.', summaryHi: 'पात्र असंगठित कामगार का सरकारी रिकॉर्ड बनाएं और जुड़ी योजनाएं देखें।',
    whatFor: 'Home-based workers, domestic workers, farm workers, street vendors, gig workers, and other unorganised workers.',
    nextStep: 'Keep Aadhaar and an Aadhaar-linked mobile number ready, or visit a CSC for assisted registration.', nextStepHi: 'आधार और आधार से जुड़ा मोबाइल रखें, या CSC में जाकर मदद से पंजीकरण करें।',
    officialUrl: 'https://eshram.gov.in/', keywords: ['eshram', 'worker', 'unorganised', 'labour', 'कामगार', 'मजदूर', 'ई-श्रम', 'தொழிலாளர்', 'வேலைக்காரர்', 'కార్మికుడు', 'కూలీ', 'मजूर', 'ಕೆಲಸಗಾರ', 'ಕಾರ್ಮಿಕ', 'કામદાર', 'തൊഴിലാളി', 'ਮਜ਼ਦੂਰ', 'ଶ୍ରମିକ', 'শ্ৰমিক', 'مزدور'],
  },
  {
    id: 'digilocker', category: 'money', icon: 'documents', priority: 3,
    title: 'DigiLocker documents', titleHi: 'डिजिलॉकर कागज़',
    summary: 'Access and share eligible digital government documents from one place.', summaryHi: 'एक जगह से अपने उपलब्ध डिजिटल सरकारी कागज़ देखें और साझा करें।',
    whatFor: 'Keeping certificates and identity documents available on a phone when the issuing department supports DigiLocker.',
    nextStep: 'Open DigiLocker and use only the official sign-in flow. Never share your OTP with anyone.', nextStepHi: 'डिजिलॉकर का आधिकारिक साइन-इन ही इस्तेमाल करें। OTP किसी को न बताएं।',
    officialUrl: 'https://www.digilocker.gov.in/', keywords: ['document', 'certificate', 'digilocker', 'दस्तावेज़', 'सर्टिफिकेट', 'डिजिलॉकर'],
  },
  {
    id: 'umang', category: 'money', icon: 'documents', priority: 4,
    title: 'UMANG government services', titleHi: 'उमंग सरकारी सेवाएं',
    summary: 'Find many central and state government services in one official app and website.', summaryHi: 'कई केंद्रीय और राज्य सरकारी सेवाएं एक आधिकारिक ऐप और वेबसाइट पर खोजें।',
    whatFor: 'A single place to discover services when you are not sure which department handles a task.',
    nextStep: 'Search the service by name and verify the department before entering personal details.', nextStepHi: 'सेवा का नाम खोजें और निजी जानकारी भरने से पहले विभाग की जांच करें।',
    officialUrl: 'https://web.umang.gov.in/', keywords: ['umang', 'government service', 'service', 'सेवा', 'उमंग'],
  },
  {
    id: 'myscheme', category: 'family', icon: 'discover', priority: 2,
    title: 'MyScheme personalised scheme finder', titleHi: 'MyScheme योजना खोज',
    summary: 'Answer a few questions to discover central and state schemes that may fit you.', summaryHi: 'कुछ सवालों के जवाब देकर अपने लिए उपयुक्त केंद्रीय और राज्य योजनाएं खोजें।',
    whatFor: 'When you do not know the scheme name but know your need, age, work, family, or location.',
    nextStep: 'Use the official finder, then open the department’s official page before applying.', nextStepHi: 'आधिकारिक finder इस्तेमाल करें, फिर आवेदन से पहले विभाग का असली पेज खोलें।',
    officialUrl: 'https://www.myscheme.gov.in/', keywords: ['scheme', 'benefit', 'my scheme', 'योजना', 'लाभ', 'मायस्कीम'],
  },
  {
    id: 'india-gov', category: 'family', icon: 'discover', priority: 3,
    title: 'National Portal of India', titleHi: 'भारत सरकार का राष्ट्रीय पोर्टल',
    summary: 'Search official central and state services, schemes, helplines, and information.', summaryHi: 'केंद्रीय और राज्य सेवाएं, योजनाएं, हेल्पलाइन और सरकारी जानकारी खोजें।',
    whatFor: 'The broadest official starting point when a service is not listed here or may be state-specific.',
    nextStep: 'Search in simple words and check the department name and official website address.', nextStepHi: 'सरल शब्दों में खोजें और विभाग का नाम व वेबसाइट का पता जांचें।',
    officialUrl: 'https://www.india.gov.in/', keywords: ['india portal', 'government', 'state scheme', 'national portal', 'सरकारी वेबसाइट', 'राज्य योजना'],
  },
  {
    id: 'ncs', category: 'work', icon: 'work', priority: 1,
    title: 'National Career Service', titleHi: 'राष्ट्रीय करियर सेवा',
    summary: 'Search jobs, career centres, counselling, internships, and jobs for women.', summaryHi: 'नौकरी, करियर सेंटर, सलाह, इंटर्नशिप और महिलाओं के लिए काम खोजें।',
    whatFor: 'Women looking for a job, career guidance, training connection, or a safer official job search.',
    nextStep: 'Search by job and location. NCS says its employment services are free; do not pay an employer to apply.', nextStepHi: 'काम और जगह से खोजें। NCS की सेवाएं मुफ्त हैं; आवेदन के लिए किसी को पैसे न दें।',
    phone: '1514', officialUrl: 'https://www.ncs.gov.in/', keywords: ['job', 'jobs', 'career', 'employment', 'work', 'नौकरी', 'काम', 'रोजगार', 'வேலை', 'வேலைவாய்ப்பு', 'ఉద్యోగం', 'పని', 'नोकरी', 'रोजगार', 'ಕೆಲಸ', 'ಉದ್ಯೋಗ', 'નોકરી', 'રોજગાર', 'ജോലി', 'തൊഴിൽ', 'ਨੌਕਰੀ', 'ਰੁਜ਼ਗਾਰ', 'ଚାକିରି', 'ରୋଜଗାର', 'চাকৰি', 'নিয়োগ', 'ملازمت', 'روزگار'],
  },
  {
    id: 'skill-india', category: 'work', icon: 'skills', priority: 2,
    title: 'Skill India Digital Hub', titleHi: 'स्किल इंडिया डिजिटल हब',
    summary: 'Find skill courses, training, and certification pathways.', summaryHi: 'कौशल कोर्स, ट्रेनिंग और प्रमाणपत्र के रास्ते खोजें।',
    whatFor: 'Women who want to learn a trade, improve a skill, or prepare for work.',
    nextStep: 'Choose a course, read the provider details, and confirm any fee before enrolling.', nextStepHi: 'कोर्स चुनें, संस्था की जानकारी पढ़ें और दाखिला लेने से पहले फीस जांचें।',
    officialUrl: 'https://www.skillindiadigital.gov.in/', keywords: ['skill', 'course', 'training', 'skill india', 'कौशल', 'कोर्स', 'ट्रेनिंग', 'திறன்', 'பயிற்சி', 'కోర్సు', 'శిక్షణ', 'कौशल्य', 'प्रशिक्षण', 'ಕೌಶಲ್ಯ', 'ತರಬೇತಿ', 'કૌશલ્ય', 'તાલીમ', 'നൈപുണ്യം', 'പരിശീലനം', 'ਹੁਨਰ', 'ਸਿਖਲਾਈ', 'ଦକ୍ଷତା', 'ପ୍ରଶିକ୍ଷଣ', 'দক্ষতা', 'প্ৰশিক্ষণ', 'مہارت', 'تربیت'],
  },
  {
    id: 'mgnrega', category: 'work', icon: 'work', priority: 3,
    title: 'MGNREGA rural work', titleHi: 'मनरेगा ग्रामीण काम',
    summary: 'Learn how rural households can ask for work through the local programme process.', summaryHi: 'ग्रामीण परिवार स्थानीय कार्यक्रम के तहत काम कैसे मांग सकते हैं, यह जानें।',
    whatFor: 'Adults in rural households who need wage work and want to ask at the Gram Panchayat.',
    nextStep: 'Go to your Gram Panchayat or authorised local office and ask for a job card or work demand process.', nextStepHi: 'ग्राम पंचायत या अधिकृत कार्यालय जाकर जॉब कार्ड और काम मांगने की प्रक्रिया पूछें।',
    officialUrl: 'https://nrega.nic.in/', keywords: ['mgnrega', 'nrega', 'rural work', 'job card', 'मनरेगा', 'रोजगार', 'जॉब कार्ड'],
  },
  {
    id: 'aajeevika-shg', category: 'business', icon: 'business', priority: 1,
    title: 'DAY-NRLM / Aajeevika self-help groups', titleHi: 'दीनदयाल आजीविका स्वयं सहायता समूह',
    summary: 'Find information about rural women’s self-help groups and livelihoods.', summaryHi: 'ग्रामीण महिलाओं के स्वयं सहायता समूह और आजीविका की जानकारी लें।',
    whatFor: 'Women who want to join or understand a local self-help group and livelihood support.',
    nextStep: 'Ask your Gram Panchayat, block office, or local SHG federation for the nearest group.', nextStepHi: 'ग्राम पंचायत, ब्लॉक कार्यालय या स्थानीय SHG संघ से नज़दीकी समूह पूछें।',
    officialUrl: 'https://aajeevika.gov.in/', keywords: ['self help group', 'shg', 'aajeevika', 'livelihood', 'स्वयं सहायता समूह', 'आजीविका', 'सखी'],
  },
  {
    id: 'wep', category: 'business', icon: 'business', priority: 2,
    title: 'Women Entrepreneurship Platform', titleHi: 'महिला उद्यमिता प्लेटफॉर्म',
    summary: 'Find mentorship, funding, learning, and business support for women entrepreneurs.', summaryHi: 'महिला उद्यमियों के लिए मेंटरशिप, फंडिंग, सीख और व्यवसाय सहायता खोजें।',
    whatFor: 'Women starting or growing a business, including home-based and small businesses.',
    nextStep: 'Explore the knowledge, mentorship, and partner support available on WEP.', nextStepHi: 'WEP पर उपलब्ध ज्ञान, मेंटरशिप और पार्टनर सहायता देखें।',
    officialUrl: 'https://wep.gov.in/', keywords: ['business', 'entrepreneur', 'women entrepreneur', 'wep', 'व्यवसाय', 'उद्यमी', 'महिला उद्यमी'],
  },
  {
    id: 'stand-up-india', category: 'business', icon: 'business', priority: 3,
    title: 'Stand-Up India', titleHi: 'स्टैंड-अप इंडिया',
    summary: 'Explore bank-loan support for eligible women and SC/ST entrepreneurs starting a greenfield enterprise.', summaryHi: 'पात्र महिला और SC/ST उद्यमियों के नए व्यवसाय के लिए बैंक ऋण सहायता की जानकारी लें।',
    whatFor: 'A woman planning a new business who needs to understand the bank-linked process.',
    nextStep: 'Use the official portal to understand the application route and speak with a participating bank.', nextStepHi: 'आधिकारिक पोर्टल पर प्रक्रिया समझें और भाग लेने वाले बैंक से बात करें।',
    officialUrl: 'https://www.standupmitra.in/', keywords: ['stand up india', 'loan', 'business loan', 'उद्यम ऋण', 'लोन', 'बिजनेस'],
  },
  {
    id: 'pm-svanidhi', category: 'business', icon: 'business', priority: 4,
    title: 'PM SVANidhi street-vendor support', titleHi: 'PM स्वनिधि स्ट्रीट वेंडर सहायता',
    summary: 'Find official working-capital support information for eligible street vendors.', summaryHi: 'पात्र स्ट्रीट वेंडरों के लिए कार्यशील पूंजी सहायता की जानकारी लें।',
    whatFor: 'Women street vendors and small sellers who need to understand the official support route.',
    nextStep: 'Ask your urban local body or use the official portal; confirm the current terms before applying.', nextStepHi: 'नगर निकाय से पूछें या आधिकारिक पोर्टल खोलें; आवेदन से पहले वर्तमान शर्तें जांचें।',
    officialUrl: 'https://pmsvanidhi.mohua.gov.in/', keywords: ['street vendor', 'svanidhi', 'vendor', 'ठेला', 'फेरी', 'विक्रेता', 'स्वनिधि'],
  },
  {
    id: 'pmegp', category: 'business', icon: 'business', priority: 5,
    title: 'PMEGP self-employment support', titleHi: 'PMEGP स्वरोज़गार सहायता',
    summary: 'Explore the official route for credit-linked support to start a micro enterprise.', summaryHi: 'सूक्ष्म व्यवसाय शुरू करने के लिए ऋण से जुड़ी सहायता की आधिकारिक जानकारी लें।',
    whatFor: 'Women planning a small manufacturing or service business.',
    nextStep: 'Read the eligibility and application guidance on the official PMEGP portal before preparing a project plan.', nextStepHi: 'प्रोजेक्ट योजना बनाने से पहले PMEGP पोर्टल पर पात्रता और प्रक्रिया पढ़ें।',
    officialUrl: 'https://www.kviconline.gov.in/pmegpeportal/', keywords: ['pmegp', 'self employment', 'enterprise', 'micro business', 'स्वरोजगार', 'लघु उद्योग'],
  },
  {
    id: 'pm-kisan', category: 'business', icon: 'family', priority: 6,
    title: 'PM-KISAN farmer support', titleHi: 'PM-किसान किसान सहायता',
    summary: 'Check the official farmer-support portal and registration or status information.', summaryHi: 'किसान सहायता पोर्टल पर पंजीकरण और स्थिति की जानकारी देखें।',
    whatFor: 'Women farmers and landholding families who need to check farmer services.',
    nextStep: 'Use the official portal or ask the local agriculture office to verify land and beneficiary details.', nextStepHi: 'आधिकारिक पोर्टल या कृषि कार्यालय से भूमि और लाभार्थी जानकारी जांचें।',
    officialUrl: 'https://pmkisan.gov.in/', keywords: ['farmer', 'farm', 'pm kisan', 'agriculture', 'किसान', 'खेती', 'कृषि'],
  },
  {
    id: 'pmay-g', category: 'family', icon: 'family', priority: 6,
    title: 'PM Awas Yojana - Gramin', titleHi: 'प्रधानमंत्री आवास योजना - ग्रामीण',
    summary: 'Find official information about rural housing support and the local verification process.', summaryHi: 'ग्रामीण आवास सहायता और स्थानीय सत्यापन प्रक्रिया की आधिकारिक जानकारी लें।',
    whatFor: 'Rural families who need to understand whether housing support is available through the local government process.',
    nextStep: 'Ask your Gram Panchayat or block office to explain the current housing list and verification steps.', nextStepHi: 'ग्राम पंचायत या ब्लॉक कार्यालय से वर्तमान आवास सूची और सत्यापन के कदम पूछें।',
    officialUrl: 'https://pmayg.nic.in/', keywords: ['house', 'housing', 'home', 'awas', 'घर', 'आवास', 'मकान'],
  },
  {
    id: 'sukanya-samriddhi', category: 'family', icon: 'family', priority: 4,
    title: 'Sukanya Samriddhi Account', titleHi: 'सुकन्या समृद्धि खाता',
    summary: 'Learn about the small-savings account for a girl child through authorised channels.', summaryHi: 'बालिका के लिए अधिकृत चैनल से छोटी बचत खाते की जानकारी लें।',
    whatFor: 'Parents or guardians saving for a girl child’s future.',
    nextStep: 'Ask an India Post office or authorised bank for the current account rules and documents.', nextStepHi: 'डाकघर या अधिकृत बैंक से वर्तमान नियम और कागज़ पूछें।',
    officialUrl: 'https://www.indiapost.gov.in/', keywords: ['girl child', 'sukanya', 'savings', 'daughter', 'बेटी', 'बचत', 'सुकन्या'],
  },
  {
    id: 'scholarships', category: 'family', icon: 'skills', priority: 5,
    title: 'National Scholarship Portal', titleHi: 'राष्ट्रीय छात्रवृत्ति पोर्टल',
    summary: 'Find and apply for eligible scholarships through the official student portal.', summaryHi: 'आधिकारिक छात्र पोर्टल पर पात्र छात्रवृत्तियां खोजें और आवेदन करें।',
    whatFor: 'Girls and women in school, college, or eligible training programmes.',
    nextStep: 'Search by course, category, and state. Keep the official application dates in view.', nextStepHi: 'कोर्स, श्रेणी और राज्य से खोजें। आवेदन की आधिकारिक तारीख जरूर देखें।',
    officialUrl: 'https://scholarships.gov.in/', keywords: ['scholarship', 'student', 'education', 'college', 'छात्रवृत्ति', 'पढ़ाई', 'कॉलेज'],
  },
];

export function getResourceById(id) {
  return RESOURCE_CATALOG.find((resource) => resource.id === id) || RESOURCE_CATALOG[0];
}
